User API's PR
TL-Backend/aerpace-ecosystem-user-service pull request #3
Opened 2023-08-28 12:55 UTC by vikas143516

Implemented below Api's
+ Add user
+ Edit user
+ List users

2023-08-29 05:56 UTC, bharathkandula99 commented
![image](https://github.com/TL-Backend/aerpace-ecosystem-user-service/assets/62982842/86792ee1-e897-4411-8289-0154d2972b34)
Try to fix these

2023-08-29 17:10 UTC, naveen-repos requested changes
In the error response function we don't need that many or conditions. It is in edfora multiple people wrote that for years so they that many or conditions

As we are starting we need to maintain single formate.

2023-08-29 17:10 UTC, naveen-repos commented on src/controllers/user/users.middleware.js
> +      errorsList.push(messages.errorMessages.PAGE_LIMIT_MESSAGE);
Page Limit and Page Number should be mandatory params. Where user should be paginated.

2023-08-29 17:10 UTC, naveen-repos commented on src/controllers/user/users.middleware.js
> +      errorsList.push(messages.errorMessages.INVALID_USER_TYPE_MESSAGE);
Didn't get this validation. Do you want to check the user_type?

2023-08-29 17:26 UTC, naveen-repos commented on src/controllers/user/users.helper.js
> +      logger.error(err);
We don't need catch here. As you have catch for whole function it handle it. And your doing only single job that can take care

2023-08-29 17:31 UTC, naveen-repos commented on src/controllers/user/users.helper.js
> +    if (!userData.success) {
Please check this code

2023-08-29 17:32 UTC, naveen-repos commented on src/controllers/user/users.helper.js
> +    return false;
When it is a helper function please maintain the response formate unique

2023-08-29 17:43 UTC, naveen-repos commented on src/controllers/user/users.helper.js
> +        return {
Can we please avoid these then and catch. Please stick with async and await only through out the project

2023-08-29 17:45 UTC, naveen-repos commented on src/controllers/user/users.helper.js
> +      success: false,
Log the error occurred

Following helper function also don't have logging of exception occurred in catch block. Please for those also

2023-09-06 10:42 UTC, naveen-repos commented on src/controllers/user/user.helper.js
> +    if (!user.user_type) user.user_type = 'USER' + user.email;
No this wrong.

2023-09-06 10:57 UTC, naveen-repos commented on src/controllers/user/user.helper.js
> +        totalPages: totalPages !== 0 ? totalPages : 1,
The variable in the response should be in the snake case

2023-09-06 11:00 UTC, naveen-repos commented on src/controllers/user/user.middleware.js
> +    }
`!id.startsWith('u')` you're doing check shre and again checking at line `112`

2023-09-06 11:19 UTC, naveen-repos commented on src/controllers/user/user.middleware.js
> +    if (role_id?.startsWith('r')) {
duplication check

2023-09-06 11:20 UTC, naveen-repos commented on src/controllers/user/user.middleware.js
> +      message: error,
For an instance of string you're sending instance of the exception.

2023-09-06 11:21 UTC, naveen-repos commented on src/controllers/user/user.helper.js
> +    if (!user.user_type) user.user_type = 'USER' + user.email;
The user_type = "USER" only.

2023-09-06 13:54 UTC, naveen-repos approved these changes

2023-09-06 13:54 UTC, merged